// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMsg.proto

package org.mygame.fingertip.gamemsg;

public final class GameMsg {
  private GameMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 消息代号
   * </pre>
   *
   * Protobuf enum {@code GameMsg.MsgCode}
   */
  public enum MsgCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *用户登录
     * </pre>
     *
     * <code>USER_LOGIN_CMD = 0;</code>
     */
    USER_LOGIN_CMD(0),
    /**
     * <pre>
     *用户登录返回
     * </pre>
     *
     * <code>USER_LOGIN_RESULT = 1;</code>
     */
    USER_LOGIN_RESULT(1),
    /**
     * <pre>
     *用户退出
     * </pre>
     *
     * <code>USER_QUIT_RESULT = 2;</code>
     */
    USER_QUIT_RESULT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *用户登录
     * </pre>
     *
     * <code>USER_LOGIN_CMD = 0;</code>
     */
    public static final int USER_LOGIN_CMD_VALUE = 0;
    /**
     * <pre>
     *用户登录返回
     * </pre>
     *
     * <code>USER_LOGIN_RESULT = 1;</code>
     */
    public static final int USER_LOGIN_RESULT_VALUE = 1;
    /**
     * <pre>
     *用户退出
     * </pre>
     *
     * <code>USER_QUIT_RESULT = 2;</code>
     */
    public static final int USER_QUIT_RESULT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgCode forNumber(int value) {
      switch (value) {
        case 0: return USER_LOGIN_CMD;
        case 1: return USER_LOGIN_RESULT;
        case 2: return USER_QUIT_RESULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgCode>() {
            public MsgCode findValueByNumber(int number) {
              return MsgCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.mygame.fingertip.gamemsg.GameMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgCode[] VALUES = values();

    public static MsgCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GameMsg.MsgCode)
  }

  public interface UserLoginCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameMsg.UserLoginCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * <pre>
   * 用户登录
   * /////////////////////////////////////////////////////////////////////
   * 指令
   * </pre>
   *
   * Protobuf type {@code GameMsg.UserLoginCmd}
   */
  public  static final class UserLoginCmd extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GameMsg.UserLoginCmd)
      UserLoginCmdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserLoginCmd.newBuilder() to construct.
    private UserLoginCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserLoginCmd() {
      userName_ = "";
      password_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserLoginCmd();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserLoginCmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserLoginCmd_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserLoginCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd.class, org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object userName_;
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>string password = 2;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd)) {
        return super.equals(obj);
      }
      org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd other = (org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd) obj;

      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 用户登录
     * /////////////////////////////////////////////////////////////////////
     * 指令
     * </pre>
     *
     * Protobuf type {@code GameMsg.UserLoginCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameMsg.UserLoginCmd)
        org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserLoginCmd_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserLoginCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd.class, org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd.Builder.class);
      }

      // Construct using org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userName_ = "";

        password_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserLoginCmd_descriptor;
      }

      @java.lang.Override
      public org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd getDefaultInstanceForType() {
        return org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd.getDefaultInstance();
      }

      @java.lang.Override
      public org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd build() {
        org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd buildPartial() {
        org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd result = new org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd(this);
        result.userName_ = userName_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd) {
          return mergeFrom((org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd other) {
        if (other == org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 1;</code>
       * @return The userName.
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 1;</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 1;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 1;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <pre>
       * 用户密码
       * </pre>
       *
       * <code>string password = 2;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用户密码
       * </pre>
       *
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户密码
       * </pre>
       *
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户密码
       * </pre>
       *
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户密码
       * </pre>
       *
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GameMsg.UserLoginCmd)
    }

    // @@protoc_insertion_point(class_scope:GameMsg.UserLoginCmd)
    private static final org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd();
    }

    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserLoginCmd>
        PARSER = new com.google.protobuf.AbstractParser<UserLoginCmd>() {
      @java.lang.Override
      public UserLoginCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserLoginCmd(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserLoginCmd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserLoginCmd> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.mygame.fingertip.gamemsg.GameMsg.UserLoginCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserLoginResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameMsg.UserLoginResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用户 Id,
     * 如果是 -1 则说明登录失败
     * </pre>
     *
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 2;</code>
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 2;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     * 英雄形象
     * </pre>
     *
     * <code>string heroAvatar = 3;</code>
     * @return The heroAvatar.
     */
    java.lang.String getHeroAvatar();
    /**
     * <pre>
     * 英雄形象
     * </pre>
     *
     * <code>string heroAvatar = 3;</code>
     * @return The bytes for heroAvatar.
     */
    com.google.protobuf.ByteString
        getHeroAvatarBytes();
  }
  /**
   * <pre>
   * 结果
   * </pre>
   *
   * Protobuf type {@code GameMsg.UserLoginResult}
   */
  public  static final class UserLoginResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GameMsg.UserLoginResult)
      UserLoginResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserLoginResult.newBuilder() to construct.
    private UserLoginResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserLoginResult() {
      userName_ = "";
      heroAvatar_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserLoginResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserLoginResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              heroAvatar_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserLoginResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserLoginResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult.class, org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <pre>
     * 用户 Id,
     * 如果是 -1 则说明登录失败
     * </pre>
     *
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    public int getUserId() {
      return userId_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 2;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 2;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEROAVATAR_FIELD_NUMBER = 3;
    private volatile java.lang.Object heroAvatar_;
    /**
     * <pre>
     * 英雄形象
     * </pre>
     *
     * <code>string heroAvatar = 3;</code>
     * @return The heroAvatar.
     */
    public java.lang.String getHeroAvatar() {
      java.lang.Object ref = heroAvatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        heroAvatar_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 英雄形象
     * </pre>
     *
     * <code>string heroAvatar = 3;</code>
     * @return The bytes for heroAvatar.
     */
    public com.google.protobuf.ByteString
        getHeroAvatarBytes() {
      java.lang.Object ref = heroAvatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        heroAvatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeUInt32(1, userId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (!getHeroAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, heroAvatar_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (!getHeroAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, heroAvatar_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult)) {
        return super.equals(obj);
      }
      org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult other = (org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (!getHeroAvatar()
          .equals(other.getHeroAvatar())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + HEROAVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getHeroAvatar().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 结果
     * </pre>
     *
     * Protobuf type {@code GameMsg.UserLoginResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameMsg.UserLoginResult)
        org.mygame.fingertip.gamemsg.GameMsg.UserLoginResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserLoginResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserLoginResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult.class, org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult.Builder.class);
      }

      // Construct using org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        userName_ = "";

        heroAvatar_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserLoginResult_descriptor;
      }

      @java.lang.Override
      public org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult getDefaultInstanceForType() {
        return org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult.getDefaultInstance();
      }

      @java.lang.Override
      public org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult build() {
        org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult buildPartial() {
        org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult result = new org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult(this);
        result.userId_ = userId_;
        result.userName_ = userName_;
        result.heroAvatar_ = heroAvatar_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult) {
          return mergeFrom((org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult other) {
        if (other == org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getHeroAvatar().isEmpty()) {
          heroAvatar_ = other.heroAvatar_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       * 用户 Id,
       * 如果是 -1 则说明登录失败
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @return The userId.
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 用户 Id,
       * 如果是 -1 则说明登录失败
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户 Id,
       * 如果是 -1 则说明登录失败
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 2;</code>
       * @return The userName.
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 2;</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 2;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 2;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object heroAvatar_ = "";
      /**
       * <pre>
       * 英雄形象
       * </pre>
       *
       * <code>string heroAvatar = 3;</code>
       * @return The heroAvatar.
       */
      public java.lang.String getHeroAvatar() {
        java.lang.Object ref = heroAvatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          heroAvatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 英雄形象
       * </pre>
       *
       * <code>string heroAvatar = 3;</code>
       * @return The bytes for heroAvatar.
       */
      public com.google.protobuf.ByteString
          getHeroAvatarBytes() {
        java.lang.Object ref = heroAvatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          heroAvatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 英雄形象
       * </pre>
       *
       * <code>string heroAvatar = 3;</code>
       * @param value The heroAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setHeroAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        heroAvatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 英雄形象
       * </pre>
       *
       * <code>string heroAvatar = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeroAvatar() {
        
        heroAvatar_ = getDefaultInstance().getHeroAvatar();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 英雄形象
       * </pre>
       *
       * <code>string heroAvatar = 3;</code>
       * @param value The bytes for heroAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setHeroAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        heroAvatar_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GameMsg.UserLoginResult)
    }

    // @@protoc_insertion_point(class_scope:GameMsg.UserLoginResult)
    private static final org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult();
    }

    public static org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserLoginResult>
        PARSER = new com.google.protobuf.AbstractParser<UserLoginResult>() {
      @java.lang.Override
      public UserLoginResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserLoginResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserLoginResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserLoginResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.mygame.fingertip.gamemsg.GameMsg.UserLoginResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserQuitResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameMsg.UserQuitResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 退出用户 Id
     * </pre>
     *
     * <code>uint32 quitUserId = 1;</code>
     * @return The quitUserId.
     */
    int getQuitUserId();
  }
  /**
   * <pre>
   * 
   * 用户退场
   * /////////////////////////////////////////////////////////////////////
   * 
   * XXX 注意: 用户退场不需要指令, 因为是在断开服务器的时候执行
   * 
   * 结果
   * </pre>
   *
   * Protobuf type {@code GameMsg.UserQuitResult}
   */
  public  static final class UserQuitResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GameMsg.UserQuitResult)
      UserQuitResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserQuitResult.newBuilder() to construct.
    private UserQuitResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserQuitResult() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserQuitResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserQuitResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              quitUserId_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserQuitResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserQuitResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult.class, org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult.Builder.class);
    }

    public static final int QUITUSERID_FIELD_NUMBER = 1;
    private int quitUserId_;
    /**
     * <pre>
     * 退出用户 Id
     * </pre>
     *
     * <code>uint32 quitUserId = 1;</code>
     * @return The quitUserId.
     */
    public int getQuitUserId() {
      return quitUserId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (quitUserId_ != 0) {
        output.writeUInt32(1, quitUserId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (quitUserId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, quitUserId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult)) {
        return super.equals(obj);
      }
      org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult other = (org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult) obj;

      if (getQuitUserId()
          != other.getQuitUserId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUITUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getQuitUserId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 
     * 用户退场
     * /////////////////////////////////////////////////////////////////////
     * 
     * XXX 注意: 用户退场不需要指令, 因为是在断开服务器的时候执行
     * 
     * 结果
     * </pre>
     *
     * Protobuf type {@code GameMsg.UserQuitResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameMsg.UserQuitResult)
        org.mygame.fingertip.gamemsg.GameMsg.UserQuitResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserQuitResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserQuitResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult.class, org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult.Builder.class);
      }

      // Construct using org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        quitUserId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mygame.fingertip.gamemsg.GameMsg.internal_static_GameMsg_UserQuitResult_descriptor;
      }

      @java.lang.Override
      public org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult getDefaultInstanceForType() {
        return org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult.getDefaultInstance();
      }

      @java.lang.Override
      public org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult build() {
        org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult buildPartial() {
        org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult result = new org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult(this);
        result.quitUserId_ = quitUserId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult) {
          return mergeFrom((org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult other) {
        if (other == org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult.getDefaultInstance()) return this;
        if (other.getQuitUserId() != 0) {
          setQuitUserId(other.getQuitUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int quitUserId_ ;
      /**
       * <pre>
       * 退出用户 Id
       * </pre>
       *
       * <code>uint32 quitUserId = 1;</code>
       * @return The quitUserId.
       */
      public int getQuitUserId() {
        return quitUserId_;
      }
      /**
       * <pre>
       * 退出用户 Id
       * </pre>
       *
       * <code>uint32 quitUserId = 1;</code>
       * @param value The quitUserId to set.
       * @return This builder for chaining.
       */
      public Builder setQuitUserId(int value) {
        
        quitUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 退出用户 Id
       * </pre>
       *
       * <code>uint32 quitUserId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuitUserId() {
        
        quitUserId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GameMsg.UserQuitResult)
    }

    // @@protoc_insertion_point(class_scope:GameMsg.UserQuitResult)
    private static final org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult();
    }

    public static org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserQuitResult>
        PARSER = new com.google.protobuf.AbstractParser<UserQuitResult>() {
      @java.lang.Override
      public UserQuitResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserQuitResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserQuitResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserQuitResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.mygame.fingertip.gamemsg.GameMsg.UserQuitResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameMsg_UserLoginCmd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GameMsg_UserLoginCmd_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameMsg_UserLoginResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GameMsg_UserLoginResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameMsg_UserQuitResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GameMsg_UserQuitResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rGameMsg.proto\022\007GameMsg\"2\n\014UserLoginCmd" +
      "\022\020\n\010userName\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"G\n\017" +
      "UserLoginResult\022\016\n\006userId\030\001 \001(\r\022\020\n\010userN" +
      "ame\030\002 \001(\t\022\022\n\nheroAvatar\030\003 \001(\t\"$\n\016UserQui" +
      "tResult\022\022\n\nquitUserId\030\001 \001(\r*J\n\007MsgCode\022\022" +
      "\n\016USER_LOGIN_CMD\020\000\022\025\n\021USER_LOGIN_RESULT\020" +
      "\001\022\024\n\020USER_QUIT_RESULT\020\002B\036\n\034org.mygame.fi" +
      "ngertip.gamemsgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GameMsg_UserLoginCmd_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GameMsg_UserLoginCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GameMsg_UserLoginCmd_descriptor,
        new java.lang.String[] { "UserName", "Password", });
    internal_static_GameMsg_UserLoginResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GameMsg_UserLoginResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GameMsg_UserLoginResult_descriptor,
        new java.lang.String[] { "UserId", "UserName", "HeroAvatar", });
    internal_static_GameMsg_UserQuitResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GameMsg_UserQuitResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GameMsg_UserQuitResult_descriptor,
        new java.lang.String[] { "QuitUserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
